spring.application.name=vetapp

#BBDD
spring.datasource.url=jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres?user=postgres.bixdljpamugqsjzbkiyz&password=9Cdk9nYAEgFlyOez
#spring.datasource.username=postgres
#spring.datasource.password=9Cdk9nYAEgFlyOez

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
