-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.adoption_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  animal_id uuid NOT NULL,
  adopter_id uuid NOT NULL,
  adoption_date date NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  deleted_by uuid,
  updated_by uuid,
  created_by uuid,
  CONSTRAINT adoption_history_pkey PRIMARY KEY (id),
  CONSTRAINT fk_adoption_animal FOREIGN KEY (animal_id) REFERENCES public.animal(id),
  CONSTRAINT fk_adoption_adopter FOREIGN KEY (adopter_id) REFERENCES public.users(id),
  CONSTRAINT fk_adoption_deleted_by FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.animal (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying,
  species character varying NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'INTAKE'::animal_status,
  animal_image text,
  client_id uuid,
  center_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  deleted_by uuid,
  updated_by uuid,
  created_by uuid,
  CONSTRAINT animal_pkey PRIMARY KEY (id),
  CONSTRAINT fk_animal_client FOREIGN KEY (client_id) REFERENCES public.users(id),
  CONSTRAINT fk_animal_center FOREIGN KEY (center_id) REFERENCES public.centers(id),
  CONSTRAINT fk_animal_deleted_by FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.animal_transfers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  animal_id uuid NOT NULL,
  from_center_id uuid,
  to_center_id uuid NOT NULL,
  initiated_by uuid,
  transfer_type USER-DEFINED NOT NULL DEFAULT 'TEMPORARY'::transfer_type,
  reason text,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  ended_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT animal_transfers_pkey PRIMARY KEY (id),
  CONSTRAINT animal_transfers_animal_id_fkey FOREIGN KEY (animal_id) REFERENCES public.animal(id),
  CONSTRAINT animal_transfers_from_center_id_fkey FOREIGN KEY (from_center_id) REFERENCES public.centers(id),
  CONSTRAINT animal_transfers_to_center_id_fkey FOREIGN KEY (to_center_id) REFERENCES public.centers(id),
  CONSTRAINT animal_transfers_initiated_by_fkey FOREIGN KEY (initiated_by) REFERENCES public.users(id)
);
CREATE TABLE public.appointments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  appointment_date date NOT NULL,
  appointment_time time without time zone NOT NULL,
  reason text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::appointment_status,
  receptionist_id uuid,
  client_id uuid NOT NULL,
  animal_id uuid NOT NULL,
  room_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  deleted_by uuid,
  updated_by uuid,
  created_by uuid,
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_appointments_receptionist FOREIGN KEY (receptionist_id) REFERENCES public.users(id),
  CONSTRAINT fk_appointments_client FOREIGN KEY (client_id) REFERENCES public.users(id),
  CONSTRAINT fk_appointments_animal FOREIGN KEY (animal_id) REFERENCES public.animal(id),
  CONSTRAINT fk_appointments_room FOREIGN KEY (room_id) REFERENCES public.rooms(id),
  CONSTRAINT fk_appointments_deleted_by FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.centers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  address character varying NOT NULL,
  city character varying NOT NULL,
  postcode character varying NOT NULL,
  center_type USER-DEFINED NOT NULL DEFAULT 'CLINIC'::center_type,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  deleted_by uuid,
  updated_by uuid,
  created_by uuid,
  CONSTRAINT centers_pkey PRIMARY KEY (id),
  CONSTRAINT fk_centers_deleted_by FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.rooms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  center_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  created_by uuid,
  CONSTRAINT rooms_pkey PRIMARY KEY (id),
  CONSTRAINT fk_rooms_center FOREIGN KEY (center_id) REFERENCES public.centers(id)
);
CREATE TABLE public.treatments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  description text NOT NULL,
  medication text,
  dosage character varying,
  appointment_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  deleted_by uuid,
  updated_by uuid,
  created_by uuid,
  CONSTRAINT treatments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_treatments_appointment FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT fk_treatments_employee FOREIGN KEY (employee_id) REFERENCES public.users(id),
  CONSTRAINT fk_treatments_deleted_by FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  dni character varying NOT NULL UNIQUE,
  user_name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  password character varying,
  role USER-DEFINED NOT NULL DEFAULT 'CLIENT'::user_role,
  user_image text,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  phone_number character varying NOT NULL,
  salary numeric,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  deleted_by uuid,
  auth_id uuid UNIQUE,
  updated_by uuid,
  created_by uuid,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT fk_users_deleted_by FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.working (
  user_id uuid NOT NULL,
  center_id uuid NOT NULL,
  start_date date,
  end_date date,
  updated_by uuid,
  created_by uuid,
  CONSTRAINT working_pkey PRIMARY KEY (user_id, center_id),
  CONSTRAINT fk_working_user FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_working_center FOREIGN KEY (center_id) REFERENCES public.centers(id)
);